# Generated by Django 3.2.1 on 2021-05-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0007_remove_student_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('dept', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('sections', models.CharField(max_length=20)),
                ('subjects', models.CharField(max_length=40)),
            ],
        ),
    ]
