# Generated by Django 3.2.1 on 2021-06-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0010_auto_20210603_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
