# Generated by Django 3.2.1 on 2021-06-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0012_alter_sections_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
