# Generated by Django 3.2.1 on 2021-06-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0014_alter_sections_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sections',
            old_name='dept',
            new_name='deptt',
        ),
    ]
