# Generated by Django 3.2.1 on 2021-06-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0016_rename_deptt_sections_dept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sections',
            old_name='section',
            new_name='sect',
        ),
    ]
