# Generated by Django 3.2.1 on 2021-05-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='admindata',
        ),
    ]
