# Generated by Django 3.2.1 on 2021-05-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0005_alter_student_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
