# Generated by Django 3.2.1 on 2021-06-07 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0017_rename_section_sections_sect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sections',
            name='dept',
        ),
        migrations.AddField(
            model_name='sections',
            name='department',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sections',
            name='sect',
            field=models.CharField(max_length=50),
        ),
    ]
