# Generated by Django 3.2.1 on 2021-06-08 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0018_auto_20210607_1403'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sections',
            new_name='sec',
        ),
    ]
